//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Provisioning.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PCResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PCResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Provisioning.Common.PCResources", typeof(PCResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving Key: {0}.
        /// </summary>
        internal static string AppSettings_GetKey {
            get {
                return ResourceManager.GetString("AppSettings_GetKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key {0} was not found in the config file..
        /// </summary>
        internal static string AppSettings_KeyNotFound {
            get {
                return ResourceManager.GetString("AppSettings_KeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Occured while reading the configruation file. The Error is {0}.
        /// </summary>
        internal static string ConfigurationError_Reading {
            get {
                return ResourceManager.GetString("ConfigurationError_Reading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did not find Master Template file {0}.
        /// </summary>
        internal static string Exception_MasterTemplateNotFound {
            get {
                return ResourceManager.GetString("Exception_MasterTemplateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passed argument is a zero-length string or contains only whitespace..
        /// </summary>
        internal static string Exception_Message_EmptyString_Arg {
            get {
                return ResourceManager.GetString("Exception_Message_EmptyString_Arg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RepositoryManagerType is missing from the configuration file.  Please update the configuration file..
        /// </summary>
        internal static string Exception_SiteRequest_Manager_Missing_Config_Message {
            get {
                return ResourceManager.GetString("Exception_SiteRequest_Manager_Missing_Config_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TemplateProviderType is missing from the configuration file.  Please update the configuration file..
        /// </summary>
        internal static string Exception_Template_Provider_Missing_Config_Message {
            get {
                return ResourceManager.GetString("Exception_Template_Provider_Missing_Config_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error loading Provisioning Connector. Exception {0}&quot;.
        /// </summary>
        internal static string FileConnectorBase_Exception {
            get {
                return ResourceManager.GetString("FileConnectorBase_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create site request list {0} in Site Collection {1}. The Exception is {2}.
        /// </summary>
        internal static string SiteRequest_List_Creation_Error {
            get {
                return ResourceManager.GetString("SiteRequest_List_Creation_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created site request list {0} in Site Collection {1}.
        /// </summary>
        internal static string SiteRequest_List_Creation_SuccessFull {
            get {
                return ResourceManager.GetString("SiteRequest_List_Creation_SuccessFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Site Request Submitted for URL {0} successfull.
        /// </summary>
        internal static string SiteRequestNew_Successfull {
            get {
                return ResourceManager.GetString("SiteRequestNew_Successfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating Site Request Status for URL {0} to status {1}.
        /// </summary>
        internal static string SiteRequestUpdate_Successfull {
            get {
                return ResourceManager.GetString("SiteRequestUpdate_Successfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory created instance {0}.
        /// </summary>
        internal static string SiteTemplate_Factory_Created_Instance {
            get {
                return ResourceManager.GetString("SiteTemplate_Factory_Created_Instance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create instance {0} exception {1}.
        /// </summary>
        internal static string SiteTemplate_Factory_Created_Instance_Exception {
            get {
                return ResourceManager.GetString("SiteTemplate_Factory_Created_Instance_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error loading Template Provider. Exception {0}&quot;.
        /// </summary>
        internal static string TemplateProviderBase_Exception_Message {
            get {
                return ResourceManager.GetString("TemplateProviderBase_Exception_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an Error Processing Template.Config. Exception: {0} StackTrace: {1}..
        /// </summary>
        internal static string XMLTemplateManager_Error {
            get {
                return ResourceManager.GetString("XMLTemplateManager_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found Master Template file {0}.
        /// </summary>
        internal static string XMLTemplateManager_File_Found {
            get {
                return ResourceManager.GetString("XMLTemplateManager_File_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.config was not found: {0}.
        /// </summary>
        internal static string XMLTemplateManager_File_NotFound {
            get {
                return ResourceManager.GetString("XMLTemplateManager_File_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded Configuration File {0} for templates.
        /// </summary>
        internal static string XMLTemplateManager_Loaded_ConfigFile {
            get {
                return ResourceManager.GetString("XMLTemplateManager_Loaded_ConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to read Template Configuration File {0}.
        /// </summary>
        internal static string XMLTemplateManager_TryRead_ConfigFile {
            get {
                return ResourceManager.GetString("XMLTemplateManager_TryRead_ConfigFile", resourceCulture);
            }
        }
    }
}
